services:
  - type: web
    name: shreeguru-system
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHON_VERSION_OVERRIDE
        value: 3.11.9
